[tool.nbqa.config]
isort = "pyproject.toml"
black = "pyproject.toml"

[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1

[tool.nbqa.addopts]
isort = ["--treat-comment-as-code", "# %%"]
pyupgrade = ["--py38-plus"]

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
fail-under = 90
exclude = ["setup.py", "docs", "build", "tests"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*", "^fit$", "^transform$"]
verbose = 1
quiet = false
whitelist-regex = []
color = true

[tool.isort]
profile = "black"
line_length = 88
force_grid_wrap = 0
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
indent = '    '
skip = ['.tox', '.venv', 'build', 'dist']
extra_standard_library = ['setuptools', 'pkg_resources']
known_test = 'pytest'
known_first_party = "dstoolbox"
known_third_party = ["altair", "dstoolbox", "environs", "importlib_metadata", "jinja2", "loguru", "numpy", "pandas", "pytest", "setuptools", "shap", "sklearn", "snowflake", "sparklines", "sqlalchemy", "tenacity", "xgboost"]
sections = ['FUTURE', 'STDLIB', 'TEST', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
default_section = 'THIRDPARTY'

[tool.flakehell]
# QUICKFIX, see https://github.com/flakehell/flakehell/issues/10#issuecomment-822720074
extended_default_ignore=[]

[tool.vulture]
paths = ["src"]
exclude = []
ignore_decorators = []
ignore_names = []
make_whitelist = true
min_confidence = 80
sort_by_size = true
verbose = true
